spring.application.name=queueless
spring.datasource.url=jdbc:mysql://localhost:3306/queueless_db
spring.datasource.username=root
spring.datasource.password=your_password

>>>>>>> 47aef1edfa6695141c3c0383941dcd9858cad4f3

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=8080